name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test_data_analyzer_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --prefix applications/data-analyzer-server

      - name: Run tests
        run: npm test --prefix applications/data-analyzer-server

  test_data_collector_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --prefix applications/data-analyzer-server

      - name: Run tests
        run: npm test --prefix applications/data-analyzer-server

  deploy_data_collector_server:
    needs: test_data_collector_server
    runs-on: ubuntu-latest
    if: ${{ needs.test_data_collector_server.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Second Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --prefix applications/data-collector-server

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo $HEROKU_API_KEY | base64 --decode | tr -d '\n' | heroku login

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a data-collector-server-app
          git push heroku main

  deploy_data_analyzer_server:
    needs: test_data_analyzer_server
    runs-on: ubuntu-latest
    if: ${{ needs.test_data_analyzer_server.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Second Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --prefix applications/data-analyzer-server

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo $HEROKU_API_KEY | base64 --decode | tr -d '\n' | heroku login

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a data-analyzer-server-app
          git push heroku main

  deploy_frontend_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install --prefix applications/frontend-server

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo $HEROKU_API_KEY | base64 --decode | tr -d '\n' | heroku login

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a frontend-server-app
          git push heroku main
